import User from "../model/userModel.js";
import bcrypt from "bcrypt";

/**
 * GET PROFILE (READ)
 * Retrieves the logged-in user's details, excluding the password.
 */
export const getProfile = async (req, res) => {
  try {
    const userId = req.user.id;
    
    const user = await User.findByPk(userId, {
      attributes: { exclude: ['userPassword'] }
    });
    
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }
    
    res.status(200).json({
      message: "Profile retrieved successfully",
      user: user
    });
  } catch (error) {
    console.error("Error fetching profile:", error);
    res.status(500).json({ message: "Server error", error: error.message });
  }
};

/**
 * UPDATE PROFILE IMAGE
 * Saves the file path generated by Multer to the user's record.
 */
export const updateProfileImage = async (req, res) => {
  try {
    const userId = req.user.id;

    if (!req.file) {
      return res.status(400).json({ message: "No image file provided" });
    }

    // Path string to store in the database
    const imagePath = `/uploads/${req.file.filename}`;

    const user = await User.findByPk(userId);
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    // Update the image column in the database
    await user.update({ image: imagePath });

    res.status(200).json({
      message: "Profile image updated successfully",
      imageUrl: imagePath
    });
  } catch (error) {
    console.error("Error updating profile image:", error);
    res.status(500).json({ message: "Server error", error: error.message });
  }
};

/**
 * UPDATE PROFILE DATA
 * Updates general user information like name, email, and location.
 */
export const updateProfile = async (req, res) => {
  try {
    const userId = req.user.id;
    const {
      userName,
      userEmail,
      phone,
      location,
      age,
      bloodGroup,
      totalDonations,
      lastDonation
    } = req.body;

    const user = await User.findByPk(userId);
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    // Prevent duplicate emails if email is being updated
    if (userEmail && userEmail !== user.userEmail) {
      const existingUser = await User.findOne({ 
        where: { userEmail: userEmail } 
      });
      if (existingUser) {
        return res.status(400).json({ message: "Email already in use" });
      }
    }

    // Consolidate update data
    const updateData = {};
    if (userName !== undefined) updateData.userName = userName;
    if (userEmail !== undefined) updateData.userEmail = userEmail;
    if (phone !== undefined) updateData.phone = phone;
    if (location !== undefined) updateData.location = location;
    if (age !== undefined) updateData.age = age;
    if (bloodGroup !== undefined) updateData.bloodGroup = bloodGroup;
    if (totalDonations !== undefined) updateData.totalDonations = totalDonations;
    if (lastDonation !== undefined) updateData.lastDonation = lastDonation;

    await user.update(updateData);

    const updatedUser = await User.findByPk(userId, {
      attributes: { exclude: ['userPassword'] }
    });

    res.status(200).json({
      message: "Profile updated successfully",
      user: updatedUser
    });
  } catch (error) {
    console.error("Error updating profile:", error);
    res.status(500).json({ message: "Server error", error: error.message });
  }
};

/**
 * CHANGE PASSWORD
 * Verifies current password and hashes the new one before saving.
 */
export const changePassword = async (req, res) => {
  try {
    const userId = req.user.id;
    const { currentPassword, newPassword } = req.body;

    if (!currentPassword || !newPassword) {
      return res.status(400).json({ message: "Please provide current and new password" });
    }

    const user = await User.findByPk(userId);
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    const isMatch = await bcrypt.compare(currentPassword, user.userPassword);
    if (!isMatch) {
      return res.status(400).json({ message: "Current password is incorrect" });
    }

    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(newPassword, salt);
    
    await user.update({ userPassword: hashedPassword });

    res.status(200).json({ message: "Password changed successfully" });
  } catch (error) {
    console.error("Error changing password:", error);
    res.status(500).json({ message: "Server error", error: error.message });
  }
};

/**
 * DELETE PROFILE
 */
export const deleteProfile = async (req, res) => {
  try {
    const userId = req.user.id;

    const user = await User.findByPk(userId);
    if (!user) {
      return res.status(404).json({ message: "User not found" });
    }

    await user.destroy();

    res.status(200).json({ message: "Profile deleted successfully" });
  } catch (error) {
    console.error("Error deleting profile:", error);
    res.status(500).json({ message: "Server error", error: error.message });
  }
};

/**
 * GET ALL PROFILES (ADMIN ONLY)
 */
export const getAllProfiles = async (req, res) => {
  try {
    if (req.user.role !== 'admin') {
      return res.status(403).json({ message: "Access denied. Admins only." });
    }

    const users = await User.findAll({
      attributes: { exclude: ['userPassword'] }
    });
    
    res.status(200).json(users);
  } catch (error) {
    console.error("Error fetching all profiles:", error);
    res.status(500).json({ message: "Server error", error: error.message });
  }
};